# Generated by Django 5.0.2 on 2024-03-08 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField()),
            ],
        ),
    ]
